Country-Integration/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Store Country Details</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Country-Integration/force-app/main/default/objects/Country__c/fields/Acronym__c.field-meta.xml
<CustomField>
    <fullName>Acronym__c</fullName>
    <label>Acronym</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Country-Integration/force-app/main/default/objects/Country__c/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <label>Alpha2Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Country-Integration/force-app/main/default/objects/Country__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <label>Alpha3Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Country-Integration/force-app/main/default/objects/Country_Key_Details__c/Country_Key_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country API Details</label>
</CustomObject>

Country-Integration/force-app/main/default/objects/Country_Key_Details__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Assignment/force-app/main/default/classes/CountryInfoSyncBatchTest.cls
@isTest
private class CountryInfoSyncBatchTest {
    @isTest
    static void testBatch() {
       insert new Country_Key_Details__c(Name = 'Key', Key__c = '1234');
        List<Country__c> countryList = new List<Country__c>();
        
        for(Integer i = 0 ; i<2 ; i++){
            countryList.add(new Country__c(Name = 'Afghanistan' , Alpha2Code__c = '1234', Alpha3Code__c = '4567', Capital_City__c = 'laurence', Region__c = 'Africa'));
        }
        
        INSERT countryList;
        // Start the batch job
        Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CountryInfoSyncMock());  
        CountryInfoSyncBatch batch = new CountryInfoSyncBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        // Verify that the batch job updated and Created the records correctly
        System.assertEquals([SELECT Alpha2Code__c, Alpha3Code__c, Capital_City__c, Region__c, Acronym__c, Name
                                             FROM Country__c].size(), 3);
        
    }
}